[profile.default]
src = 'solidity/src'
out = 'solidity/out'
test = 'solidity/test'
libs = ['solidity/lib']
solc_version = "0.8.16"

[fmt]
 line_length = 100
 number_underscore = "thousands"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config